"""Write a reproducibility manifest for the feasibility outputs (step 33).

Reads the funnel and per-patient CSVs written by step 30, recomputes the funnel
from the same event inventory to capture the headline counts, hashes the
derived CSVs with sha256, and writes ``results/manifest.json``.

The manifest lets a reader who reruns steps 20 and 30 confirm that they
regenerated bit-identical derived outputs and the same headline counts. Only
derived, aggregate files are hashed; raw waveform data and the row-level event
inventory are never hashed or shipped (PhysioNet Data Use Agreement).

Examples
--------
::

    uv run python scripts/33_write_manifest.py \\
        --events-dir data/interim/events \\
        --feasibility-dir results/feasibility \\
        --out results/manifest.json
"""

from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path

from loguru import logger

from cuffcrt.analysis.funnel import PRIMARY_PHASE3_S, SENSITIVITY_PHASE3_S, aggregate_funnel
from cuffcrt.analysis.manifest import build_manifest, write_manifest

# Reuse the inventory loader from step 30 (numeric-prefixed file, not importable
# as a normal module name).
_STEP30 = Path(__file__).with_name("30_aggregate_funnel.py")
_spec = importlib.util.spec_from_file_location("_step30", _STEP30)
assert _spec is not None and _spec.loader is not None
_step30 = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_step30)
load_inventory = _step30.load_inventory


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--events-dir",
        type=Path,
        default=Path("data/interim/events"),
        help="Directory of per-record event parquets from step 20.",
    )
    parser.add_argument(
        "--feasibility-dir",
        type=Path,
        default=Path("results/feasibility"),
        help="Directory holding funnel.csv and per_patient_summary.csv from step 30.",
    )
    parser.add_argument(
        "--sensitivity-dir",
        type=Path,
        default=Path("results/sensitivity"),
        help="Directory holding sensitivity_sweep.csv from step 31_sensitivity_sweep.",
    )
    parser.add_argument(
        "--alignment-dir",
        type=Path,
        default=Path("results/alignment_split_half"),
        help="Directory holding alignment_split_half_results.csv from step 32.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("results/manifest.json"),
        help="Output manifest path (default results/manifest.json).",
    )
    parser.add_argument(
        "--inventory-source",
        type=str,
        default="data/interim/events (regenerated by steps 20+30)",
        help="Human-readable label for the inventory source (no absolute paths).",
    )
    parser.add_argument(
        "--primary-phase3-s",
        type=float,
        default=PRIMARY_PHASE3_S,
        help=f"Primary reperfusion-envelope threshold in seconds (default {PRIMARY_PHASE3_S:g}).",
    )
    parser.add_argument(
        "--sensitivity-phase3-s",
        type=float,
        default=SENSITIVITY_PHASE3_S,
        help=(
            "Sensitivity reperfusion-envelope threshold in seconds "
            f"(default {SENSITIVITY_PHASE3_S:g})."
        ),
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Build and write the reproducibility manifest.

    Returns
    -------
    int
        Process exit code (0 on success, 2 on missing inputs).
    """
    args = _parse_args(argv)

    funnel_csv = args.feasibility_dir / "funnel.csv"
    per_patient_csv = args.feasibility_dir / "per_patient_summary.csv"
    targets = [funnel_csv, per_patient_csv]
    missing = [p for p in targets if not p.exists()]
    if missing:
        logger.error("missing step-30 outputs: {}; run step 30 first.", missing)
        return 2

    # Optional extras: include the sensitivity sweep and the alignment split-half
    # outputs when present. These are skipped (with a log line) rather than
    # raising so the manifest can still be generated on demo runs that do not
    # produce them.
    sensitivity_csv = args.sensitivity_dir / "sensitivity_sweep.csv"
    alignment_csv = args.alignment_dir / "alignment_split_half_results.csv"
    for extra in (sensitivity_csv, alignment_csv):
        if extra.exists():
            targets.append(extra)
        else:
            logger.warning("optional manifest target missing, skipping: {}", extra)

    try:
        inventory = load_inventory(args.events_dir)
    except FileNotFoundError as exc:
        logger.error("{}", exc)
        return 2

    result = aggregate_funnel(
        inventory,
        primary_phase3_s=args.primary_phase3_s,
        sensitivity_phase3_s=args.sensitivity_phase3_s,
    )
    manifest = build_manifest(
        result,
        targets,
        inventory_source=args.inventory_source,
        repo_root=Path.cwd(),
    )
    write_manifest(manifest, args.out)

    logger.info("wrote {}", args.out)
    for entry in manifest["files"]:
        logger.info("  {} sha256={} ({} bytes)", entry["name"], entry["sha256"], entry["bytes"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
